package bolatito

// DBResponseStructure contains the information for the response expected from `SHOW SLAVE STATUS` query result
type DBResponseStructure struct {
	SlaveIOState              string  `db:"Slave_IO_State"`
	MasterHost                string  `db:"Master_Host"`
	MasterUser                string  `db:"Master_User"`
	MasterPort                string  `db:"Master_Port"`
	ConnectRetry              string  `db:"Connect_Retry"`
	MasterLogFile             string  `db:"Master_Log_File"`
	ReadMasterLogPos          string  `db:"Read_Master_Log_Pos"`
	RelayLogFile              string  `db:"Relay_Log_File"`
	RelayLogPos               string  `db:"Relay_Log_Pos"`
	RelayMasterLogFile        string  `db:"Relay_Master_Log_File"`
	SlaveIORunning            string  `db:"Slave_IO_Running"`
	SlaveSQLRunning           string  `db:"Slave_SQL_Running"`
	ReplicateDoDB             string  `db:"Replicate_Do_DB"`
	ReplicateIgnoreDB         string  `db:"Replicate_Ignore_DB"`
	ReplicateDoTable          string  `db:"Replicate_Do_Table"`
	ReplicateIgnoreTable      string  `db:"Replicate_Ignore_Table"`
	ReplicateWildDoTable      string  `db:"Replicate_Wild_Do_Table"`
	ReplicateWildIgnoreTable  string  `db:"Replicate_Wild_Ignore_Table"`
	LastErrno                 string  `db:"Last_Errno"`
	LastError                 string  `db:"Last_Error"`
	SkipCounter               string  `db:"Skip_Counter"`
	ExecMasterLogPos          string  `db:"Exec_Master_Log_Pos"`
	RelayLogSpace             string  `db:"Relay_Log_Space"`
	UntilCondition            string  `db:"Until_Condition"`
	UntilLogFile              string  `db:"Until_Log_File"`
	UntilLogPos               string  `db:"Until_Log_Pos"`
	MasterSSLAllowed          string  `db:"Master_SSL_Allowed"`
	MasterSSLCAFile           string  `db:"Master_SSL_CA_File"`
	MasterSSLCAPath           string  `db:"Master_SSL_CA_Path"`
	MasterSSLCert             string  `db:"Master_SSL_Cert"`
	MasterSSLCipher           string  `db:"Master_SSL_Cipher"`
	MasterSSLKey              string  `db:"Master_SSL_Key"`
	SecondsBehindMaster       string  `db:"Seconds_Behind_Master"`
	MasterSSLVerifyServerCert string  `db:"Master_SSL_Verify_Server_Cert"`
	LastIOErrno               string  `db:"Last_IO_Errno"`
	LastIOError               string  `db:"Last_IO_Error"`
	LastSQLErrno              string  `db:"Last_SQL_Errno"`
	LastSQLError              string  `db:"Last_SQL_Error"`
	ReplicateIgnoreServerIds  string  `db:"Replicate_Ignore_Server_Ids"`
	MasterServerID            string  `db:"Master_Server_Id"`
	MasterUUID                string  `db:"Master_UUID"`
	MasterInfoFile            string  `db:"Master_Info_File"`
	SQLDelay                  string  `db:"SQL_Delay"`
	SQLRemainingDelay         []uint8 `db:"SQL_Remaining_Delay"`
	SlaveSQLRunningState      string  `db:"Slave_SQL_Running_State"`
	MasterRetryCount          string  `db:"Master_Retry_Count"`
	MasterBind                string  `db:"Master_Bind"`
	LastIOErrorTimestamp      string  `db:"Last_IO_Error_Timestamp"`
	LastSQLErrorTimestamp     string  `db:"Last_SQL_Error_Timestamp"`
	MasterSSLCrl              string  `db:"Master_SSL_Crl"`
	MasterSSLCrlpath          string  `db:"Master_SSL_Crlpath"`
	RetrievedGtidSet          string  `db:"Retrieved_Gtid_Set"`
	ExecutedGtidSet           string  `db:"Executed_Gtid_Set"`
	AutoPosition              string  `db:"Auto_Position"`
}
